spring:
  zipkin:
    base-url: http://101.201.76.21:9411
    discovery-client-enabled: false
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
  datasource:
    username: root
    password: pqhloyxb111
    url: jdbc:mysql://101.201.76.21:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
  application:
    name: gulimall-member
  thymeleaf:
    cache: false
  redis:
    host: 101.201.76.21
    port: 6379
    password: pqhyxb
  session:
    store-type: redis
  cache:
    type: redis
    redis:
      time-to-live: -1
      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true